=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-THPD-BME280/AsksinPP_addon_control_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="AsksinPP_addon_control_file">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="creator" type="xs:string"/>
        <xs:element name="device_name" type="xs:string"/>
        <xs:element name="device_description" type="xs:string"/>
        <xs:element name="device_small_case_name" type="xs:string"/>
        <xs:element name="version" type="xs:string"/>
        <xs:element ref="translated_datapoints"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="translated_datapoints">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datapoint" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datapoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="index" type="xs:string"/>
        <xs:element name="channel_type" type="xs:string"/>
        <xs:element name="string_identifier" type="xs:string"/>
        <xs:element name="translated_string" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-AQ-THPD-SHT85/HB-UNI-SENSOR-AQ-THPD-SHT85_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-THPD-SHT85</device_name>
  <device_description>Sensor THPD</device_description>
  <device_small_case_name>hb-uni-sensor-THPD-SHT85</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="OPERATING_VOLTAGE">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
      <datapoint name="MY_HUMIDITY">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBHumidity</string_identifier>
        <translated_string>Rel. Luftfeuchtigkeit</translated_string>
      </datapoint>
      <datapoint name="DEWPOINT">
        <index>3</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBDewpoint</string_identifier>
        <translated_string>Taupunkt</translated_string>
      </datapoint>
      <datapoint name="VAPOR_CONCENTRATION">
        <index>4</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBVaporConcentration</string_identifier>
        <translated_string>Abs. Luftfeuchtigkeit</translated_string>
      </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-AQ-BME680_KF_DEBUG/HB-UNI-SENSOR-AQ-BME680_KF_DEBUG_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-AQ-BME680_KF_DEBUG</device_name>
  <device_description>universeller Luftgütesensor mit Kalman-Filter</device_description>
  <device_small_case_name>hb-uni-sensor-AQ-BME680_KF_DEBUG</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="AQ_LEVEL">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAirQualityLevel</string_identifier>
        <translated_string>Luftgütegrad</translated_string>
      </datapoint>
      <datapoint name="AQ_LOG10">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAirQualityLog10</string_identifier>
        <translated_string>Luftqualität Log10</translated_string>
      </datapoint>
      <datapoint name="AQ_COMP_GAS_RES_RAW">
        <index>3</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAQ_COMP_GAS_RES_RAW</string_identifier>
        <translated_string>T/aH kompensierter Gaswiderstand</translated_string>
      </datapoint>
      <datapoint name="AQ_COMP_GAS_RES_MIN">
        <index>4</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAQ_COMP_GAS_RES_MIN</string_identifier>
        <translated_string>untere Normalisierungsreferenz des T/aH kompensierter Gaswiderstands</translated_string>
      </datapoint>
      <datapoint name="AQ_COMP_GAS_RES_MAX">
        <index>5</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAQ_COMP_GAS_RES_MAX</string_identifier>
        <translated_string>obere Normalisierungsreferenz des T/aH kompensierter Gaswiderstands</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>6</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
    <datapoint name="ALTITUDE_ABOVE_SEA_LEVEL">
      <index>7</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBAltitudeAboveSealevel</string_identifier>
      <translated_string>Höhe über NN</translated_string>
    </datapoint>
    <datapoint name="TRANSMIT_TIME_INTERVAL">
      <index>8</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBTransmitTimeIntervall</string_identifier>
      <translated_string>Sendeintervall</translated_string>
    </datapoint>
    <datapoint name="MY_HUMIDITY">
      <index>9</index>
      <channel_type>WEATHER</channel_type>
      <string_identifier>stringTableHBHumidity</string_identifier>
      <translated_string>Rel. Luftfeuchtigkeit</translated_string>
    </datapoint>
    <datapoint name="TemperatureOffset">
        <index>10</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBTemperatureOffset</string_identifier>
        <translated_string>Temperaturoffset</translated_string>
      </datapoint>
      <datapoint name="HumidityOffset">
        <index>11</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBHumidityOffset</string_identifier>
        <translated_string>Luftfeuchtigkeitsoffset</translated_string>
      </datapoint>
      <datapoint name="PressureOffset">
        <index>12</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBPressureOffset</string_identifier>
        <translated_string>Luftdruckoffset</translated_string>
      </datapoint>
    <datapoint name="max_decay_factor_upper_limit">
        <index>13</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBmax_decay_factor_upper_limit</string_identifier>
        <translated_string>relative untere Schwelle der Abklingfunktion</translated_string>
      </datapoint>
      <datapoint name="max_increase_factor_lower_limit">
        <index>14</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBmax_increase_factor_lower_limit</string_identifier>
        <translated_string>relative obere Schwelle der Aufklingfunktion</translated_string>
      </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-CO2-SCD30/HB-UNI-SENSOR-CO2-SCD30_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-CO2-SCD30</device_name>
  <device_description>Sensor Kohlendioxid</device_description>
  <device_small_case_name>hb-uni-sensor-CO2-SCD30</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="CO2">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBCO2Sensor</string_identifier>
        <translated_string>CO2 Messwert</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
      <datapoint name="ACCUMULATOR_VOLTAGE">
        <index>3</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAccumulatorVoltage</string_identifier>
        <translated_string>Akkumulatorspannung(ADC)</translated_string>
      </datapoint>
      <datapoint name="VCC_VOLTAGE">
        <index>4</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBVCCVoltage</string_identifier>
        <translated_string>VCC Spannung(ADC)</translated_string>
      </datapoint>
      <datapoint name="TemperatureOffset">
        <index>5</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBTemperatureOffset</string_identifier>
        <translated_string>Temperaturoffset</translated_string>
      </datapoint>
      <datapoint name="HumidityOffset">
        <index>6</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBHumidityOffset</string_identifier>
        <translated_string>Luftfeuchtigkeitsoffset</translated_string>
      </datapoint>
      <datapoint name="ALTITUDE_ABOVE_SEA_LEVEL">
      <index>7</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBAltitudeAboveSealevel</string_identifier>
      <translated_string>Höhe über NN</translated_string>
    </datapoint>
    <datapoint name="TRANSMIT_TIME_INTERVAL">
      <index>8</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBTransmitTimeIntervall</string_identifier>
      <translated_string>Sendeintervall</translated_string>
    </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-EXAMPLE/HB-UNI-SENSOR-EXAMPLE_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>Your_name</creator>
  <device_name>HB-UNI-Sensor-EXAMPLE</device_name>
  <device_description>universelles Testsensörchen</device_description>
  <device_small_case_name>hb-uni-sensor-EXAMPLE</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="AQ_LEVEL">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAirQualityLevel</string_identifier>
        <translated_string>Luftgütegrad</translated_string>
      </datapoint>
      <datapoint name="AQ_LOG10">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBAirQualityLog10</string_identifier>
        <translated_string>Luftqualität Log10</translated_string>
      </datapoint>
      <datapoint name="AQ_GAS_RESISTANCE_RAW">
        <index>3</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBGasResistanceRaw</string_identifier>
        <translated_string>Gaswiderstand</translated_string>
      </datapoint>
      <datapoint name="AQ_GAS_RESISTANCE_MIN">
        <index>4</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBGasResistanceMin</string_identifier>
        <translated_string>min Gaswiderstand</translated_string>
      </datapoint>
      <datapoint name="AQ_GAS_RESISTANCE_MAX">
        <index>5</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBGasResistanceMax</string_identifier>
        <translated_string>max Gaswiderstand</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>6</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
    <datapoint name="ALTITUDE_ABOVE_SEA_LEVEL">
      <index>7</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBAltitudeAboveSealevel</string_identifier>
      <translated_string>Höhe über NN</translated_string>
    </datapoint>
    <datapoint name="TRANSMIT_TIME_INTERVAL">
      <index>8</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBTransmitTimeIntervall</string_identifier>
      <translated_string>Sendeintervall</translated_string>
    </datapoint>
    <datapoint name="MY_HUMIDITY">
      <index>9</index>
      <channel_type>WEATHER</channel_type>
      <string_identifier>stringTableHBHumidity</string_identifier>
      <translated_string>Rel. Luftfeuchtigkeit</translated_string>
    </datapoint>
        <datapoint name="MY_TEST">
      <index>10</index>
      <channel_type>WEATHER</channel_type>
      <string_identifier>stringTableHBMY_TEST</string_identifier>
      <translated_string>Testzeichenfolge</translated_string>
    </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-RAD-AL53/HB-UNI-SENSOR-RAD-AL53_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4</creator>
  <device_name>HB-UNI-SENSOR-RAD-AL53</device_name>
  <device_description>Radioaktivitätssensor</device_description>
  <device_small_case_name>hb-uni-sensor-RAD-AL53</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="COUNTS_PER_HOUR">
        <index>1</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBCOUNTS_PER_HOUR</string_identifier>
        <translated_string>Zählimpulse pro h</translated_string>
      </datapoint>
      <datapoint name="COUNTS_PER_HOUR_MAX">
        <index>2</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBCOUNTS_PER_HOUR_MAX</string_identifier>
        <translated_string>Zählimpulse pro h max</translated_string>
      </datapoint>
      <datapoint name="COUNTS_PER_HOUR_FILTERED">
        <index>3</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBCOUNTS_PER_HOUR_FILTERED</string_identifier>
        <translated_string>Zählimpulse pro h filtered</translated_string>
      </datapoint>
      <datapoint name="COUNTS_PER_SAMPLE">
        <index>4</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBCOUNTS_PER_SAMPLE</string_identifier>
        <translated_string>Zählimpulse</translated_string>
      </datapoint>
        <datapoint name="ACCUMULATOR_VOLTAGE">
        <index>5</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBACCUMULATOR_VOLTAGE</string_identifier>
        <translated_string>Akkumulatorspannung(ADC)</translated_string>
      </datapoint>
      <datapoint name="AL53_SUPPLY_VOLTAGE">
        <index>6</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBAL53_SUPPLY_VOLTAGE</string_identifier>
        <translated_string>AL53 Betriebsspannung (ADC)</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>7</index>
        <channel_type>HB_MEASUREMENT_RAD</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Betriebsspannung</translated_string>
      </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-CO2-SCD30-plugged_in/HB-UNI-SENSOR-CO2-SCD30-plugged_in_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-CO2-SCD30_plugged_in</device_name>
  <device_description>Sensor Kohlendioxid Netzbetrieb</device_description>
  <device_small_case_name>hb-uni-sensor-CO2-SCD30_plugged_in</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="CO2">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBCO2Sensor</string_identifier>
        <translated_string>CO2 Messwert</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
    </datapoint>
    <datapoint name="TemperatureOffset">
        <index>3</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBTemperatureOffset</string_identifier>
        <translated_string>Temperaturoffset</translated_string>
      </datapoint>
      <datapoint name="HumidityOffset">
        <index>4</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBHumidityOffset</string_identifier>
        <translated_string>Luftfeuchtigkeitsoffset</translated_string>
      </datapoint>
      <datapoint name="ALTITUDE_ABOVE_SEA_LEVEL">
      <index>5</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBAltitudeAboveSealevel</string_identifier>
      <translated_string>Höhe über NN</translated_string>
    </datapoint>
    <datapoint name="TRANSMIT_TIME_INTERVAL">
      <index>6</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBTransmitTimeIntervall</string_identifier>
      <translated_string>Sendeintervall</translated_string>
    </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-CO2-SCD30-plugged_in/HB-UNI-SENSOR-CO2-SCD30_plugged_in_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-CO2-SCD30_plugged_in</device_name>
  <device_description>Sensor Kohlendioxid Netzbetrieb</device_description>
  <device_small_case_name>hb-uni-sensor-CO2-SCD30_plugged_in</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="CO2">
        <index>1</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBCO2Sensor</string_identifier>
        <translated_string>CO2 Messwert</translated_string>
      </datapoint>
      <datapoint name="OPERATING_VOLTAGE">
        <index>2</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
    </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-TH-SHT75/HB-UNI-SENSOR-TH-SHT75_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-TH-SHT75</device_name>
  <device_description>Sensor TH</device_description>
  <device_small_case_name>hb-uni-sensor-TH-SHT75</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="OPERATING_VOLTAGE">
        <index>1</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
      <datapoint name="MY_HUMIDITY">
        <index>2</index>
        <channel_type>WEATHER</channel_type>
        <string_identifier>stringTableHBHumidity</string_identifier>
        <translated_string>Rel. Luftfeuchtigkeit</translated_string>
      </datapoint>
      <datapoint name="TRANSMIT_TIME_INTERVAL">
      <index>3</index>
      <channel_type>SKIP</channel_type>
      <string_identifier>stringTableHBTransmitTimeIntervall</string_identifier>
      <translated_string>Sendeintervall</translated_string>
    </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>
