=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-THPD-BME280/AsksinPP_addon_control_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="AsksinPP_addon_control_file">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="creator" type="xs:string"/>
        <xs:element name="device_name" type="xs:string"/>
        <xs:element name="device_description" type="xs:string"/>
        <xs:element name="device_small_case_name" type="xs:string"/>
        <xs:element name="version" type="xs:string"/>
        <xs:element ref="translated_datapoints"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="translated_datapoints">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datapoint" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datapoint">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="index" type="xs:string"/>
        <xs:element name="channel_type" type="xs:string"/>
        <xs:element name="string_identifier" type="xs:string"/>
        <xs:element name="translated_string" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FUEL4EP/HomeAutomation/AsksinPP_developments/addons/hb-ep-devices-addon/CCU_RM/AsksinPP_addon_files_generator/_work/HB-UNI-SENSOR-AQ-THPD-BME280/HB-UNI-SENSOR-THPD-BME280_addon_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<AsksinPP_addon_control_file xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AsksinPP_addon_control_file.xsd">
  <creator>FUEL4EP</creator>
  <device_name>HB-UNI-Sensor-THPD-BME280</device_name>
  <device_description>Sensor THPD</device_description>
  <device_small_case_name>hb-uni-sensor-THPD-BME280</device_small_case_name>
  <version>1.0</version>
  <translated_datapoints>
      <datapoint name="OPERATING_VOLTAGE">
        <index>1</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBBatteryVoltage</string_identifier>
        <translated_string>Batteriespannung</translated_string>
      </datapoint>
      <datapoint name="MY_HUMIDITY">
        <index>2</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBHumidity</string_identifier>
        <translated_string>Rel. Luftfeuchtigkeit</translated_string>
      </datapoint>
      <datapoint name="DEWPOINT">
        <index>3</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBDewpoint</string_identifier>
        <translated_string>Taupunkt</translated_string>
      </datapoint>
      <datapoint name="VAPOR_CONCENTRATION">
        <index>4</index>
        <device_class>WEATHER</device_class>
        <string_identifier>stringTableHBVaporConcentration</string_identifier>
        <translated_string>Abs. Luftfeuchtigkeit</translated_string>
      </datapoint>
  </translated_datapoints>
</AsksinPP_addon_control_file>
